/MyParams:
  ros__parameters:
    ang_vel: 0.7476
    controller:
    - 0.5
    - 0.7
    - 1000.0
    label_str: hola_mundo
    lin_vel: 0.17
    param_int: 65
    timer_period: 0.0
    use_sim_time: false

